apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        joshyunho/argocd-example-apps: true
        joshyunho/golang-test: true
        joshyunho/jx3-k8s: true
        joshyunho/python-test: true
        joshyunho/react-test: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        joshyunho/argocd-example-apps: merge
        joshyunho/golang-test: merge
        joshyunho/jx3-k8s: merge
        joshyunho/python-test: merge
        joshyunho/react-test: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - joshyunho/jx3-k8s
        - joshyunho/argocd-example-apps
        - joshyunho/golang-test
        - joshyunho/python-test
        - joshyunho/react-test
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - joshyunho/jx3-k8s
        - joshyunho/argocd-example-apps
        - joshyunho/golang-test
        - joshyunho/python-test
        - joshyunho/react-test
      target_url: http://lighthouse-jx.207.192.68.74.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
