apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        joshyunho/jx3-k8s: true
    plank: {}
    pod_namespace: jx
    postsubmits:
      joshyunho/argocd-example-apps:
      - agent: tekton-pipeline
        branches:
        - master
        - main
        labels:
          aadpodidbinding: tekton-bot
        name: release
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
    presubmits:
      joshyunho/argocd-example-apps:
      - agent: tekton-pipeline
        always_run: true
        context: pr-build
        labels:
          aadpodidbinding: tekton-bot
        name: pr-build
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        joshyunho/argocd-example-apps: merge
        joshyunho/jx3-k8s: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - joshyunho/jx3-k8s
        - joshyunho/argocd-example-apps
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - joshyunho/jx3-k8s
        - joshyunho/argocd-example-apps
      target_url: http://lighthouse-jx.207.192.68.74.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
